#Superuser level permissions
sudo: required
#Need docker cli preinstalled
services:
  - docker

#Installs before tests are run
before-install:
  - docker build -t spsmith86/docker-react -f Dockerfile.dev .

#Commands to run on the built container
script:
  - docker run -e CI=true spsmith86/docker-react npm run test